apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-system

resources:
  - namespace.yaml
  - crds/
  - rbac/
  - redis.yaml
  - operator.yaml

commonLabels:
  app.kubernetes.io/part-of: mcp-system
